start , stop = 1,5
sum=0
while start<=stop:
    number=int(input("ตัวเลข : "))
    sum+=number # บวกเลขที่ป้อนแต่ละรอบ
    start+=1
avg=sum/stop
print("ผลรวม = ",sum)
print("ค่าเฉลี่ย = ",avg)